import Image from "../../entities/image.js";
import imageService from "./imageService.js";
import databaseService from "../../utils/databaseService.js";
/*	
	A function that keeps the details of how image entity objects are instantiated hidden from the rest of the application.
 	If the image entity is redefined, implementing those changes will be easy.
 	Will also keep the business logic releated to creating images seperate from the entity itself.
*/
async function createImage(documentId, imageName, imageLink){
	let dbWrapper = new databaseService();
	let res;
	let tempImage;
	let imageWrapper;
	
	// Mock image object to gain access to imageService methods to check if the image is valid per the business rules.
	tempImage = new Image(0, documentId, imageName, imageLink);
	imageWrapper = new imageService(tempImage);
	
	// A couple of switch cases that determine if our image object is valid.
	switch(true){
		case !imageWrapper.getValidateImageName():
			return{
				boolean: false,
				response: "The title of the image must be between 1 and 50 characters long."
			};
		case !imageWrapper.getValidateLink():
			return{
				boolean: false,
				response: "The link of the image must be a google image link"
			};
	}
	
	// If we have a valid image we can then add it to the database.
	try{
		res = await dbWrapper.addImage(documentId, imageName, imageLink);
		if(!res.boolean){
			return{
				boolean: false,
				response: res.response
			}
		}
		
		// After adding the valid image to the database we then instantiate and return it.
		// Pass in the assigned id automatically generated by the database.
		return{
			boolean: true,
			image: new Image(res.id, documentId, imageName, imageLink)
		}
	}
	catch(error){
		console.error(error);
		return{
				boolean: false,
				response: "An unexpected error occurred."	
		}
	}
}

export default createImage;