import User from "../../entities/user.js";
import userService from "./userService.js";
import databaseService from "../../utils/databaseService.js";


/*	
	A function that keeps the details of how user entity objects are instantiated hidden from the rest of the application.
 	If the user entity is redefined, implementing those changes will be easy.
 	Will also keep the business logic releated to creating users seperate from the entity itself.
*/
async function createUser(firstName, lastName, username, password, email){
	let dbWrapper = new databaseService();
	let res;
	let tempUser;
	let userWrapper;
	
	// Mock user object to gain access to userService methods to check if the user is valid per the business rules.
	tempUser = new User(0, firstName, lastName, username, password, email);
	userWrapper = new userService(tempUser);
	
	// A series of switch cases that determine if our user object is valid.
	switch(true){
		case !userWrapper.getValidateFirstName():
			return{
				boolean: false,
				response: "First name must be between 1 and 15 characters long."
			};
		case !userWrapper.getValidateLastName():
			return{
				boolean: false,
				response: "Last name must be between 1 and 15 characters long."
			};
		case !userWrapper.getValidateUserName():
			return{
				boolean: false,
				response: "Username must be between 7 and 29 characters long."
			};
		case !userWrapper.getValidatePassword():
			return{
				boolean: false,
				response: "Password must be between 8 and 19 characters long."
			};
		case !userWrapper.getValidateEmail():
			return{
				boolean: false,
				response: "Email must contain one @ character."
			};
	}
	
	// If we have a valid user we can then add it to the database.
	try{
		res = await dbWrapper.addUser(firstName, lastName, username, password, email);
		if(!res.boolean){
			return{
				boolean: false,
				response: res.response
			}
		}
		
		// After adding the valid user to the database we then instantiate and return it.
		// Pass in the assigned id automatically generated by the database.
		return{
			boolean: true,
			user: new User(res.id, firstName, lastName, username, password, email)
		}
	}
	catch(error){
		console.error(error);
		return{
				boolean: false,
				response: "An unexpected error occurred."	
		}
	}
}

export default createUser;