import quizAttempt from "../../entities/quizAttempt.js";
import quizAttemptService from "./quizAttemptService.js";
import databaseService from "../../utils/databaseService.js";
/*	
	A function that keeps the details of how quiz attempt entity objects are instantiated hidden from the rest of the application.
 	If the quiz attempt entity is redefined, implementing those changes will be easy.
 	Will also keep the business logic releated to creating quiz attempts seperate from the entity itself.
*/
async function createQuizAttempt(userId, quizId, isFinished){
	let dbWrapper = new databaseService();
	let res;
	let tempQuizAttempt;
	let quizAttemptWrapper;
	
	// Mock quiz attempt object to gain access to quizAttempt methods to check if the quiz attempt is valid per the business rules.
	tempQuizAttempt = new quizAttempt(0, userId, quizId, isFinished);
	quizAttemptWrapper = new quizAttemptService(tempQuizAttempt);
	
	// A series of switch cases that determine if our quiz attempt object is valid.
	switch(true){
		case !quizAttemptWrapper.getValidateId():
			return{
				boolean: false,
				response: "The quiz question id must be an integer."
			};
		case !quizAttemptWrapper.getValidateUserId():
			return{
				boolean: false,
				response: "The quiz attempt user id must be an integer."
			};
		case !quizAttemptWrapper.getValidateQuizId():
			return{
				boolean: false,
				response: "The quiz attempt quiz id must be an integer."
			};
		case !quizAttemptWrapper.getValidateIsFinished():
			return{
				boolean: false,
				response: "The quiz attempt isFinished field must be a boolean."
			};
	}
	
	// If we have a valid quiz attempt we can then add it to the database.
	try{
		res = await dbWrapper.addQuizAttempt(userId, quizId, isFinished);
		if(!res.boolean){
			return{
				boolean: false,
				response: res.response
			}
		}
		
		// After adding the valid quiz attempt to the database we then instantiate and return it.
		// Pass in the assigned id automatically generated by the database.
		return{
			boolean: true,
			quizAttempt: new quizAttempt(res.id, userId, quizId, isFinished)
		}
	}
	catch(error){
		console.error(error);
		return{
				boolean: false,
				response: "An unexpected error occurred."	
		}
	}
}

export default createQuizAttempt;