import Quiz from "../../entities/quiz.js";
import quizService from "./quizService.js";
import databaseService from "../../utils/databaseService.js";
/*	
	A function that keeps the details of how quiz entity objects are instantiated hidden from the rest of the application.
 	If the quiz entity is redefined, implementing those changes will be easy.
 	Will also keep the business logic releated to creating quizzes seperate from the entity itself.
*/
async function createQuiz(moduleId, title, body){
	let dbWrapper = new databaseService();
	let res;
	let tempQuiz;
	let quizWrapper;
	
	// Mock quiz object to gain access to quizService methods to check if the quiz is valid per the business rules.
	tempQuiz = new Quiz(0, moduleId, title, body);
	quizWrapper = new quizService(tempQuiz);
	
	// A series of switch cases that determine if our quiz object is valid.
	switch(true){
		case !quizWrapper.getValidateTitle():
			return{
				boolean: false,
				response: "The title of the quiz must be between 1 and 30 characters long."
			};
		case !quizWrapper.getValidateBody():
			return{
				boolean: false,
				response: "The body of the quiz must be between 0 and 5000 characters long."
			};
	}
	
	// If we have a valid quiz we can then add it to the database.
	try{
		res = await dbWrapper.addQuiz(moduleId, title, body);
		if(!res.boolean){
			return{
				boolean: false,
				response: res.response
			}
		}
		
		// After adding the valid quiz to the database we then instantiate and return it.
		// Pass in the assigned id automatically generated by the database.
		return{
			boolean: true,
			quiz: new Quiz(res.id, moduleId, title, body)
		}
	}
	catch(error){
		console.error(error);
		return{
				boolean: false,
				response: "An unexpected error occurred."	
		}
	}
}

export default createQuiz;