import quizQuestion from "../../entities/quizQuestion.js";
import quizQuestionService from "./quizQuestionService.js";
import databaseService from "../../utils/databaseService.js";
/*	
	A function that keeps the details of how quiz question entity objects are instantiated hidden from the rest of the application.
 	If the quiz question entity is redefined, implementing those changes will be easy.
 	Will also keep the business logic releated to creating quiz questions seperate from the entity itself.
*/
async function createQuizQuestion(quizId, question, answers, correctAnswer){
	let dbWrapper = new databaseService();
	let res;
	let tempQuizQuestion;
	let quizQuestionWrapper;
	
	// Mock quiz question object to gain access to quizQuestion methods to check if the quiz question is valid per the business rules.
	tempQuizQuestion = new quizQuestion(0, quizId, question, answers, correctAnswer);
	quizQuestionWrapper = new quizQuestionService(tempQuizQuestion);
	
	// A series of switch cases that determine if our quiz question object is valid.
	switch(true){
		case !quizQuestionWrapper.getValidateQuestion():
			return{
				boolean: false,
				response: "The quiz question must be between 30 and 200 characters long."
			};
		case !quizQuestionWrapper.getValidateAnswers():
			return{
				boolean: false,
				response: "The question answer fields must be A, B, C, and D."
			};
		case !quizQuestionWrapper.getValidateAnswersLength():
			return{
				boolean: false,
				response: "The question answer lengths must be between 15 and 50 characters long."
			};
		case !quizQuestionWrapper.getValidateCorrectAnswer():
			return{
				boolean: false,
				response: "The correct answer to the question must A, B, C, or D."
			};
	}
	
	// If we have a valid quiz question we can then add it to the database.
	try{
		res = await dbWrapper.addQuizQuestion(quizId, question, answers, correctAnswer);
		if(!res.boolean){
			return{
				boolean: false,
				response: res.response
			}
		}
		
		// After adding the valid quiz question to the database we then instantiate and return it.
		// Pass in the assigned id automatically generated by the database.
		return{
			boolean: true,
			quizQuestion: new quizQuestion(res.id, quizId, question, answers, correctAnswer)
		}
	}
	catch(error){
		console.error(error);
		return{
				boolean: false,
				response: "An unexpected error occurred."	
		}
	}
}

export default createQuizQuestion;