import Module from "../../entities/module.js";
import moduleService from "./moduleService.js";
import databaseService from "../../utils/databaseService.js";
/*	
	A function that keeps the details of how module entity objects are instantiated hidden from the rest of the application.
 	If the module entity is redefined, implementing those changes will be easy.
 	Will also keep the business logic releated to creating modules seperate from the entity itself.
*/
async function createModule(title, body){
	let dbWrapper = new databaseService();
	let res;
	let tempModule;
	let moduleWrapper;
	
	// Mock module object to gain access to moduleService methods to check if the module is valid per the business rules.
	tempModule = new Module(0, title, body);
	moduleWrapper = new moduleService(tempModule);
	
	// A series of switch cases that determine if our module object is valid.
	switch(true){
		case !moduleWrapper.getValidateTitle():
			return{
				boolean: false,
				response: "The title of the module must be between 1 and 50 characters long."
			};
		case !moduleWrapper.getValidateBody():
			return{
				boolean: false,
				response: "The body of the module must be between 0 and 1000 characters long."
			};
	}
	
	// If we have a valid module we can then add it to the database.
	try{
		res = await dbWrapper.addModule(title, body);
		if(!res.boolean){
			return{
				boolean: false,
				response: res.response
			}
		}
		
		// After adding the valid module to the database we then instantiate and return it.
		// Pass in the assigned id automatically generated by the database.
		return{
			boolean: true,
			module: new Module(res.id, title, body)
		}
	}
	catch(error){
		console.error(error);
		return{
				boolean: false,
				response: "An unexpected error occurred."	
		}
	}
}

export default createModule;