import Document from "../../entities/document.js";
import documentService from "./documentService.js";
import databaseService from "../../utils/databaseService.js";
/*	
	A function that keeps the details of how document entity objects are instantiated hidden from the rest of the application.
 	If the document entity is redefined, implementing those changes will be easy.
 	Will also keep the business logic releated to creating documents seperate from the entity itself.
*/
async function createDocument(title, body, author, email, type){
	let dbWrapper = new databaseService();
	let res;
	let tempDocument;
	let documentWrapper;
	
	// Mock document object to gain access to documentService methods to check if the document is valid per the business rules.
	tempDocument = new Document(0, title, body, author, email, type);
	documentWrapper = new documentService(tempDocument);
	
	// A series of switch cases that determine if our document object is valid.
	switch(true){
		case !documentWrapper.getValidateTitle():
			return{
				boolean: false,
				response: "The title of the document must be between 1 and 50 characters long."
			};
		case !documentWrapper.getValidateBody():
			return{
				boolean: false,
				response: "The body of the document must be between 0 and 5000 characters long."
			};
		case !documentWrapper.getValidateType():
			return{
				boolean: false,
				response: "The document type must be either Manual or Procedure."
			};
	}
	
	// If we have a valid document we can then add it to the database.
	try{
		res = await dbWrapper.addDocument(title, body, author, email, type);
		if(!res.boolean){
			return{
				boolean: false,
				response: res.response
			}
		}
		
		// After adding the valid document to the database we then instantiate and return it.
		// Pass in the assigned id automatically generated by the database.
		return{
			boolean: true,
			document: new Document(res.id, title, body, author, email, type)
		}
	}
	catch(error){
		console.error(error);
		return{
				boolean: false,
				response: "An unexpected error occurred."	
		}
	}
}

export default createDocument;