import databaseService from "../../../utils/databaseService.js";
import createDocument from "../../../services/document/documentFactory.js";
import createImage from "../../../services/image/imageFactory.js";
import imageService from "../../../services/image/imageService.js";
import {expect} from "chai";

describe("Image Entity", ()=>{
	let doc;
	let img;
	let dbWrapper;
	let imageWrapper;
	let link = "https://drive.google.com/file/d/1tTz2YABm2cjrEV_5wjtuHClescuHAk8M/view?usp=drive_link";
	
	beforeEach(async ()=>{
		dbWrapper = new databaseService();
		await dbWrapper.deleteAllDocuments();
		await dbWrapper.deleteAllImages();
		
		// Used the document factory to instantiate a new document.
		doc = await createDocument(null, "UltraSite Manual", "This is a test", "test", "test123@publix.com", "Manual");
		if(doc.boolean === false){
			throw new Error(document.response);
		}
		// Extracted the document object's unique id as generated by the database to create an image object.
		doc = doc.document;
		img = await createImage(doc.id, "test", link);
		// Dependency injection. I've made this test file dependent on the imageWrapper for interacting with the image object's methods.
		imageWrapper = new imageService(img.image);
	});
	
	afterEach(async()=>{
		await dbWrapper.deleteAllDocuments();
		await dbWrapper.deleteAllImages();
	});
	
	it("should have an image name field", ()=>{
		expect(imageWrapper.getImageName()).to.equal("test");
	});
	
	it("should have a link field", ()=>{
		expect(imageWrapper.getImageLink()).to.equal(link);
	});
	
});



	
	