import quizAnswer from "../../entities/quizAnswer.js";
import quizAnswerService from "./quizAnswerService.js";
import databaseService from "../../utils/databaseService.js";
/*	
	A function that keeps the details of how quiz answer entity objects are instantiated hidden from the rest of the application.
 	If the quiz answer entity is redefined, implementing those changes will be easy.
 	Will also keep the business logic releated to creating quiz answers seperate from the entity itself.
*/
async function createQuizAnswer(quizAttemptId, quizQuestionId, answer){
	let dbWrapper = new databaseService();
	let res;
	let tempQuizAnswer;
	let quizAnswerWrapper;
	
	// Mock quiz answer object to gain access to quizAnswer methods to check if the quiz answer is valid per the business rules.
	tempQuizAnswer = new quizAnswer(0, quizAttemptId, quizQuestionId, answer);
	quizAnswerWrapper = new quizAnswerService(tempQuizAnswer);
	
	// A series of switch cases that determine if our quiz answer object is valid.
	switch(true){
		case !quizAnswerWrapper.getValidateId():
			return{
				boolean: false,
				response: "The quiz answer id must be an integer."
			};
		case !quizAnswerWrapper.getValidateQuizAttemptId():
			return{
				boolean: false,
				response: "The quiz answer quiz attempt id must be an integer."
			};
		case !quizAnswerWrapper.getValidateQuizQuestionId():
			return{
				boolean: false,
				response: "The quiz answer quiz question id must be an integer."
			};
		case !quizAnswerWrapper.getValidateAnswer():
			return{
				boolean: false,
				response: "The quiz answer answer field must be a character."
			};
	}
	
	// If we have a valid quiz answer we can then add it to the database.
	try{
		res = await dbWrapper.addQuizAnswer(quizAttemptId, quizQuestionId, answer);
		if(!res.boolean){
			return{
				boolean: false,
				response: res.response
			}
		}
		
		// After adding the valid quiz answer to the database we then instantiate and return it.
		// Pass in the assigned id automatically generated by the database.
		return{
			boolean: true,
			quizAnswer: new quizAnswer(res.id, quizAttemptId, quizQuestionId, answer)
		}
	}
	catch(error){
		console.error(error);
		return{
				boolean: false,
				response: "An unexpected error occurred."	
		}
	}
}

export default createQuizAnswer;